epizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")),
    path("", include("users.urls")),
    path("", include("order.urls")),
]

# need to add to load images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("cart/", views.cart, name="cart"),
    path("add_to_cart/<uuid:pk>", views.add_to_cart, name="add_to_cart"),
    path("remove_from_cart/<int:pk>", views.remove_from_cart, name="remove-from-cart"),
    path(
        "increase_product_quantity/<int:pk>",
        views.increase_product_quantity,
        name="increase-product-quantity",
    ),
    path(
        "reduce_product_quantity/<int:pk>",
        views.reduce_product_quantity,
        name="reduce-product-quantity",
    ),
    path(
        "change_product_quantity/",
        views.change_product_quantity,
        name="change-product-quantity",
    ),
    path("checkout", views.checkout, name="checkout"),
    path("apply_coupon/", views.coupon_apply, name="add-coupon"),
    path("remove_coupon/", views.coupon_remove, name="remove-coupon"),
    path(
        "api/checkout-session/<uuid:pk>",
        views.create_checkout_session,
        name="api_checkout_session",
    ),
    path("checkout/cash/<uuid:pk>", views.cash_checkout, name="cash-checkout"),
    path("checkout/success/", views.PaymentSuccessView.as_view(), name="success"),
    path("checkout/failed/", views.PaymentFailedView.as_view(), name="failed"),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path("", views.products, name="products"),
    path("pizza/", views.pizzas, name="pizzas"),
    path("drinks/", views.drinks, name="drinks"),
    path("sides/", views.sides, name="sides"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.SignUpView.as_view(), name="register"),
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("orders/", views.my_orders, name="my_orders"),
]

store/models.py
from django.db import models
from django.utils.safestring import mark_safe
import uuid

# Create your models here.


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    desc = models.TextField(max_length=500, blank=True, null=True)
    image = models.ImageField(blank=True, upload_to="images")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    product_category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        """Order by product category"""

        ordering = ("product_category",)

    def __str__(self):
        return self.name

    # to display image in the admin panel -> ignored by coverage
    def image_tag(self):  # pragma: no cover
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="100" height="100" />')

    image_tag.short_description = "Image"

    @property
    def get_product_variants(self):
        # reverse accessor
        variants = self.productvariant_set.all()
        return variants

    @property
    def has_variants(self):
        if self.productvariant_set.count() > 0:
            return True
        else:
            return False


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Size(models.Model):
    name = models.CharField(max_length=20, blank=True, null=True, unique=True)

    def __str__(self):
        return self.name


class ProductVariant(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"{self.title} - price: ${self.price}"

    @property
    def get_size(self):
        # return size as a string
        return str(self.size)

store/forms.py
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField(required=True)
  username = forms.CharField(required=True)
  password1 = forms.CharField(required=True)
  password2 = forms.CharField(required=True)
  
  class Meta:
      model = User
      fields = ('username', 'email', 'password1', 'password2')

store/views.py
from django.shortcuts import render
from .models import Product
from django.core.paginator import Paginator


def products(request):
    products = Product.objects.all()
    # get the keywords from the search field to alter products list
    product_name = request.GET.get("product")
    if product_name != "" and product_name is not None:
        products = products.filter(name__icontains=product_name)
    else:
        # if no item is searched input value is empty
        product_name = ""

    # pagination
    paginator = Paginator(products, 12)
    page_number = request.GET.get("page")
    products = paginator.get_page(page_number)

    # search_string is used to display input value as searched product
    context = {"products": products, "search_string": product_name}
    return render(request, "store/products.html", context=context)


def pizzas(request):
    products = Product.objects.filter(product_category__name="Pizza")
    context = {"products": products}
    return render(request, "store/pizzas.html", context=context)


def drinks(request):
    products = Product.objects.filter(product_category__name="Drink")
    context = {"products": products}
    return render(request, "store/drinks.html", context=context)


def sides(request):
    products = Product.objects.filter(product_category__name="Side")
    context = {"products": products}
    return render(request, "store/sides.html", context=context)

store/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Pizza Delivery Website</title>
  <link rel="stylesheet" href="{% static 'store/src/styles.css' %}" />
  <link rel="stylesheet" href="{% static 'store/src/customStyles.css' %}" />
  <!-- Datepicker JQuery -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css" />

  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

  <script src="{% static 'store/js/helpers.js' %}"></script>
</head>

<body class="m-0 p-0 bg-sky-100/50">
  <nav class="p-5 flex bg-cyan-200">
    <div class="flex justify-between items-center">
      <a href="{% url 'store:products' %}" class="flex">
        <img class="h-10 inline" src="{% static 'store/images/pizza.png' %}" />
        <span class="invisible md:visible ml-2 text-xl text-gray-600 cursor-pointer font-[Poppins] font-semibold">
          Crispy Pizza</span>
      </a>
    </div>
    {% with request.resolver_match.url_name as url_name %}
    <ul class="flex ml-auto items-center">
      <!-- Display orders tab if user is authenticated -->
      {% if user.is_authenticated %}
      <li
        class="text-xl mx-4 hover:text-teal-900 duration-500 {% if url_name == 'my_orders' %} text-teal-700 {% endif %}">
        <a href="{% url 'users:my_orders' %}">Orders</a>
      </li>
      {% endif %}

      <li
        class="text-xl mx-4 hover:text-teal-900 duration-500 {% if url_name == 'products' %} text-teal-700 {% endif %}">
        <a href="{% url 'store:products' %}">Home</a>
      </li>
      <li id="menu" class="text-xl">
        <div class="dropdown inline-block relative z-10">
          <button
            class="hover:text-teal-900 py-2 px-4 inline-flex items-center {% if url_name in 'pizzas, drinks, sides' %} text-teal-700 {% endif %}">
            Menu
          </button>
          <ul class="bg-cyan-200 rounded-b-xl dropdown-menu hidden absolute pt-1 left-0 right-0">
            <li class="">
              <a class="hover:text-teal-900 py-2 px-4 block whitespace-no-wrap {% if url_name == 'pizzas' %} text-teal-700 {% endif %}"
                href="{% url 'store:pizzas' %}">Pizza</a>
            </li>
            <li class="">
              <a class="hover:text-teal-900 py-2 px-4 block whitespace-no-wrap {% if url_name == 'drinks' %} text-teal-700 {% endif %}"
                href="{% url 'store:drinks' %}">Drinks</a>
            </li>
            <li class="">
              <a class="hover:text-teal-900 py-2 px-4 block whitespace-no-wrap {% if url_name == 'sides' %} text-teal-700 {% endif %}"
                href="{% url 'store:sides' %}">Sides</a>
            </li>
          </ul>
        </div>
      </li>

      {% if user.is_authenticated %}
      <li class="text-xl mx-4 hover:text-teal-900 duration-500">
        <a href="{% url 'users:logout' %}">Log Out</a>
      </li>
      {% else %}
      <li class="text-xl mx-4 hover:text-teal-900 duration-500 {% if url_name == 'login' %} text-teal-700 {% endif %}">
        <a href="{% url 'users:login' %}">Log In</a>
      </li>
      <li
        class="text-xl mx-4 hover:text-text-teal-900 duration-500 {% if url_name == 'register' %} text-teal-700 {% endif %}">
        <a href="{% url 'users:register' %}">Register</a>
      </li>
      {% endif %}
      <li class="shrink-0">
        <a href="{% url 'order:cart' %}">
          <img class="h-6" src="{% static 'store/images/cart1.png' %}" alt="cart" id="cart-image" />
        </a>
      </li>
      <li class="p-2">
        <div class="rounded-lg border border-gray-400 px-2">
          <p class="cart-count text-lg text-gray-600 font-semibold">
            {{cart_quantity}}
          </p>
        </div>
      </li>
    </ul>
    {% endwith %}
  </nav>

  {% block content %} {% endblock %}
  <!-- JQuery Datepicker -->
  <script defer src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
</body>

</html>
<script>
  // dropdown menu START
  const menu = document.querySelector("#menu");
  menu.addEventListener("mouseover", (event) => {
    const dropdownMenu = document.querySelector(".dropdown-menu");
    dropdownMenu.style.display = "block";
  });
  menu.addEventListener("mouseout", (event) => {
    const dropdownMenu = document.querySelector(".dropdown-menu");
    dropdownMenu.style.display = "none";
  });
  // dropdown menu END
  var csrftoken = "{{ csrf_token }}";
</script>

store/templates/store/drinks.html
{% extends "store/base.html" %} {% block content %} {% load static %}

<!-- Start Products List -->
<div class="flex flex-col items-center">
  <h1 class="mt-5 text-2xl text-center uppercase rounded-lg ml-5 mr-auto py-2 w-48 bg-red-200">
    Drinks
  </h1>
  <div class="grid sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 mx-3">
    {% for product in products %}
    <div class="flex flex-col m-2 bg-white rounded-xl shadow-md individual-container">
      {% if product.image %}
      <img class="h-72 w-full rounded-t-xl" src="{{ product.image.url }}" alt="" />
      {% endif %}
      <h5 class="mb-2 text-center text-2xl font-semibold tracking-tight text-gray-900">
        {{product.name}}
      </h5>

      <form action="{% url 'order:add_to_cart' product.id %}" method="post" class="text-center items-center mt-auto p-3"
        id="product-form" onkeydown="return event.key != 'Enter';">
        {% csrf_token %}
        <div class="flex my-3">
          <!-- Start Choosing Quantity -->
          <div class="flex ml-3 w-4/5">
            <button class="decrement" type="button">
              <svg class="fill-current text-gray-600 w-4" viewBox="0 0 448 512">
                <path
                  d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z" />
              </svg>
            </button>
            <input class="w-1/3 h-7 mx-2 text-center rounded-md" type="number" value="1" name="quantity" min="1"
              oninput="validity.valid||(value='1');" required />
            <button class="increment" type="button">
              <svg class="fill-current text-gray-600 w-4" viewBox="0 0 448 512">
                <path
                  d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z" />
              </svg>
            </button>
          </div>
          <!-- End Choosing Quantity -->
          <!-- Start Display Variant Prices -->
          {% if product.has_variants %}
          <div class="flex items-center font-bold text-xl text-green-500">
            {% for variant in product.get_product_variants %}
            <p
              class="prices-{{forloop.parentloop.counter}} {{variant.size}}-{{forloop.parentloop.counter}} {% if not forloop.first %} hidden {% endif %}">
              ${{variant.price|floatformat:1}}
            </p>
            {% endfor %}
          </div>
          {% else %}
          <div class="flex items-center font-bold text-xl text-green-500">
            <p>${{product.price|floatformat:1}}</p>
          </div>
          {% endif %}
          <!-- End Display Variant Prices -->
        </div>
        <!-- Start Choosing Size -->
        {% if product.has_variants %}
        <div class="flex m-2 w-1/2">
          {% for variant in product.get_product_variants%}
          <div class="flex">
            <!-- prettier-ignore -->
            <input type="radio" name="size" id="{{variant.size}}-{{forloop.parentloop.counter}}" class="peer hidden"
              value="{{variant.size}}" {% if forloop.first %} checked {% endif %} />
            <!-- prettier-ignore -->
            <label for="{{variant.size}}-{{forloop.parentloop.counter}}" class="cursor-pointer select-none rounded-xl p-2 text-sm text-center peer-checked:font-bold
              {% if forloop.counter == 1 %} peer-checked:bg-orange-100
              {% elif forloop.counter == 2 %} peer-checked:bg-orange-200
              {% elif forloop.counter == 3 %} peer-checked:bg-orange-300
              {% else %} peer-checked:bg-orange-400 {% endif %}">{{variant.size}}
            </label>
          </div>
          {% endfor %}
        </div>
        {% else %}
        <div class="p-5"></div>
        {% endif %}
        <!-- End Choosing Size -->
        <div class="flex">
          <button class="bg-green-300 hover:bg-green-500 rounded-xl w-full py-2 mt-2 js-add" type="button">
            Add to cart
          </button>
        </div>
      </form>
    </div>
    {% endfor %}
  </div>
</div>
<!-- End Products List -->
<script src="{% static 'store/js/productHelper.js' %}"></script>

{% endblock %}

store/templates/store/pizzas.html
{% extends "store/base.html" %} {% block content %} {% load static %}

<!-- Start Products List -->
<div class="flex flex-col items-center">
  <h1 class="mt-5 text-2xl text-center uppercase rounded-lg ml-5 mr-auto py-2 w-48 bg-red-200">
    Pizzas
  </h1>
  <div class="grid sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 mx-3">
    {% for product in products %}
    <div class="flex flex-col m-2 bg-white rounded-xl shadow-md individual-container">
      {% if product.image %}
      <img class="h-72 w-full rounded-t-xl" src="{{ product.image.url }}" alt="" />
      {% endif %}
      <h5 class="mb-2 text-center text-2xl font-semibold tracking-tight text-gray-900">
        {{product.name}}
      </h5>

      <form action="{% url 'order:add_to_cart' product.id %}" method="post" class="text-center items-center mt-auto p-3"
        id="product-form" onkeydown="return event.key != 'Enter';">
        {% csrf_token %}
        <div class="flex my-3">
          <!-- Start Choosing Quantity -->
          <div class="flex ml-3 w-4/5">
            <button class="decrement" type="button">
              <svg class="fill-current text-gray-600 w-4" viewBox="0 0 448 512">
                <path
                  d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z" />
              </svg>
            </button>
            <input class="w-1/3 h-7 mx-2 text-center rounded-md" type="number" value="1" name="quantity" min="1"
              oninput="validity.valid||(value='1');" required />
            <button class="increment" type="button">
              <svg class="fill-current text-gray-600 w-4" viewBox="0 0 448 512">
                <path
                  d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z" />
              </svg>
            </button>
          </div>
          <!-- End Choosing Quantity -->
          <!-- Start Display Variant Prices -->
          {% if product.has_variants %}
          <div class="flex items-center font-bold text-xl text-green-500">
            {% for variant in product.get_product_variants %}
            <p
              class="prices-{{forloop.parentloop.counter}} {{variant.size}}-{{forloop.parentloop.counter}} {% if not forloop.first %} hidden {% endif %}">
              ${{variant.price|floatformat:1}}
            </p>
            {% endfor %}
          </div>
          {% else %}
          <div class="flex items-center font-bold text-xl text-green-500">
            <p>${{product.price|floatformat:1}}</p>
          </div>
          {% endif %}
          <!-- End Display Variant Prices -->
        </div>
        <!-- Start Choosing Size -->
        {% if product.has_variants %}
        <div class="flex m-2 w-1/2">
          {% for variant in product.get_product_variants%}
          <div class="flex">
            <!-- prettier-ignore -->
            <input type="radio" name="size" id="{{variant.size}}-{{forloop.parentloop.counter}}" class="peer hidden"
              value="{{variant.size}}" {% if forloop.first %} checked {% endif %} />
            <!-- prettier-ignore -->
            <label for="{{variant.size}}-{{forloop.parentloop.counter}}" class="cursor-pointer select-none rounded-xl p-2 text-sm text-center peer-checked:font-bold
              {% if forloop.counter == 1 %} peer-checked:bg-orange-100
              {% elif forloop.counter == 2 %} peer-checked:bg-orange-200
              {% elif forloop.counter == 3 %} peer-checked:bg-orange-300
              {% else %} peer-checked:bg-orange-400 {% endif %}">{{variant.size}}
            </label>
          </div>
          {% endfor %}
        </div>
        {% else %}
        <div class="p-5"></div>
        {% endif %}
        <!-- End Choosing Size -->
        <div class="flex">
          <button class="bg-green-300 hover:bg-green-500 rounded-xl w-full py-2 mt-2 js-add" type="button">
            Add to cart
          </button>
        </div>
      </form>
    </div>
    {% endfor %}
  </div>
</div>
<!-- End Products List -->
<script src="{% static 'store/js/productHelper.js' %}"></script>

{% endblock %}

store/templates/store/products.html
{% extends "store/base.html" %} {% block content %} {% load static %}
<!-- Search Button Start -->
<div class="flex">
  <div class="ml-auto mr-2 my-2">
    <form method="GET" class="flex bg-green-200 rounded-lg" id="search-box">
      <input
        class="border-none outline-none bg-transparent focus:ring-0"
        type="text"
        placeholder="Search Products"
        name="product"
        value="{{search_string}}"
      />
      <!-- clicking on the button will submit the form -->
      <a
        class="mt-2"
        href="javascript:void(0);"
        onclick="document.getElementById('search-box').submit();"
      >
        <img class="mr-2" src="{% static 'store/images/search.svg' %}" alt="" />
      </a>
    </form>
  </div>
</div>
<!-- Search Button End -->

<!-- Start Products List -->
<div class="flex flex-col items-center">
  <h1
    class="text-2xl text-center uppercase rounded-lg ml-5 mr-auto py-2 w-48 bg-red-200"
  >
    Products
  </h1>
  <div
    class="grid sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 mx-3"
  >
    {% for product in products %}
    <div
      class="flex flex-col m-2 bg-white rounded-xl shadow-md individual-container"
    >
      {% if product.image %}
      <img
        class="h-72 w-full rounded-t-xl"
        src="{{ product.image.url }}"
        alt=""
      />
      {% endif %}
      <h5
        class="mb-2 text-center text-2xl font-semibold tracking-tight text-gray-900"
      >
        {{product.name}}
      </h5>

      <form
        action="{% url 'order:add_to_cart' product.id %}"
        method="post"
        class="text-center items-center mt-auto p-3"
        id="product-form"
        onkeydown="return event.key != 'Enter';"
      >
        <!-- to prevent form submission on 'ENTER' -->

        {% csrf_token %}
        <div class="flex my-3">
          <!-- Start Choosing Quantity -->
          <div class="flex ml-3 w-4/5">
            <button class="decrement" type="button">
              <svg class="fill-current text-gray-600 w-4" viewBox="0 0 448 512">
                <path
                  d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"
                />
              </svg>
            </button>
            <input
              class="w-1/3 h-7 mx-2 text-center rounded-md"
              type="number"
              value="1"
              name="quantity"
              min="1"
              oninput="validity.valid||(value='1');"
              required
            />
            <button class="increment" type="button">
              <svg class="fill-current text-gray-600 w-4" viewBox="0 0 448 512">
                <path
                  d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"
                />
              </svg>
            </button>
          </div>
          <!-- End Choosing Quantity -->
          <!-- Start Display Variant Prices -->
          {% if product.has_variants %}
          <div class="flex items-center font-bold text-xl text-green-500">
            {% for variant in product.get_product_variants %}
            <p
              class="prices-{{forloop.parentloop.counter}} {{variant.size}}-{{forloop.parentloop.counter}} {% if not forloop.first %} hidden {% endif %}"
            >
              ${{variant.price|floatformat:1}}
            </p>
            {% endfor %}
          </div>
          {% else %}
          <div class="flex items-center font-bold text-xl text-green-500">
            <p>${{product.price|floatformat:1}}</p>
          </div>
          {% endif %}
          <!-- End Display Variant Prices -->
        </div>
        <!-- Start Choosing Size -->
        {% if product.has_variants %}
        <div class="flex m-2 w-1/2">
          {% for variant in product.get_product_variants%}
          <div class="flex">
            <!-- prettier-ignore -->
            <input type="radio" name="size" id="{{variant.size}}-{{forloop.parentloop.counter}}" class="peer hidden"
              value="{{variant.size}}" {% if forloop.first %} checked {% endif %} />
            <!-- prettier-ignore -->
            <label for="{{variant.size}}-{{forloop.parentloop.counter}}" class="cursor-pointer select-none rounded-xl p-2 text-sm text-center peer-checked:font-bold
              {% if forloop.counter == 1 %} peer-checked:bg-orange-100
              {% elif forloop.counter == 2 %} peer-checked:bg-orange-200
              {% elif forloop.counter == 3 %} peer-checked:bg-orange-300
              {% else %} peer-checked:bg-orange-400 {% endif %}">{{variant.size}}
            </label>
          </div>
          {% endfor %}
        </div>
        {% else %}
        <div class="p-5"></div>
        {% endif %}
        <!-- End Choosing Size -->
        <div class="flex">
          <button
            class="bg-green-300 hover:bg-green-500 rounded-xl w-full py-2 mt-2 js-add"
            type="button"
          >
            Add to cart
          </button>
        </div>
      </form>
    </div>
    {% endfor %}
  </div>
</div>
<!-- End Products List -->

<!-- Start Pagination -->
<div class="flex items-center justify-center my-5">
  {% if products.has_previous %}
  <a class="text-sm font-bold items-center inline-flex relative" href="?page=1">
    <<
  </a>
  <a
    class="text-sm font-bold px-2 items-center inline-flex relative"
    href="?page={{products.previous_page_number}}"
  >
    <
  </a>
  {% else %}
  <span class="text-sm items-center inline-flex relative"> << </span>
  <span class="text-sm px-2 items-center inline-flex relative"> < </span>

  {% endif %}
  <span class="pagination"
    >{{products.number}} of {{products.paginator.num_pages}}</span
  >
  {% if products.has_next %}
  <a
    class="text-sm font-bold px-2 items-center inline-flex relative"
    href="?page={{products.next_page_number}}"
    >></a
  >
  <a
    class="text-sm font-bold items-center inline-flex relative"
    href="?page={{products.paginator.num_pages}}"
    >>></a
  >
  {% else %}
  <a
    class="text-sm px-2 items-center inline-flex relative pointer-events-none cursor-default"
    href="#"
    >></a
  >
  <a
    class="text-sm items-center inline-flex relative pointer-events-none cursor-default"
    href="#"
    >>></a
  >
  {% endif %}
</div>
<!-- End Pagination-->

<script src="{% static 'store/js/productHelper.js' %}"></script>

{% endblock %}