epizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")),
    path("", include("users.urls")),
    path("", include("order.urls")),
]

# need to add to load images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("cart/", views.cart, name="cart"),
    path("add_to_cart/<uuid:pk>", views.add_to_cart, name="add_to_cart"),
    path("remove_from_cart/<int:pk>", views.remove_from_cart, name="remove-from-cart"),
    path(
        "increase_product_quantity/<int:pk>",
        views.increase_product_quantity,
        name="increase-product-quantity",
    ),
    path(
        "reduce_product_quantity/<int:pk>",
        views.reduce_product_quantity,
        name="reduce-product-quantity",
    ),
    path(
        "change_product_quantity/",
        views.change_product_quantity,
        name="change-product-quantity",
    ),
    path("checkout", views.checkout, name="checkout"),
    path("apply_coupon/", views.coupon_apply, name="add-coupon"),
    path("remove_coupon/", views.coupon_remove, name="remove-coupon"),
    path(
        "api/checkout-session/<uuid:pk>",
        views.create_checkout_session,
        name="api_checkout_session",
    ),
    path("checkout/cash/<uuid:pk>", views.cash_checkout, name="cash-checkout"),
    path("checkout/success/", views.PaymentSuccessView.as_view(), name="success"),
    path("checkout/failed/", views.PaymentFailedView.as_view(), name="failed"),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path("", views.products, name="products"),
    path("pizza/", views.pizzas, name="pizzas"),
    path("drinks/", views.drinks, name="drinks"),
    path("sides/", views.sides, name="sides"),
]

order/forms.py
from django import forms


class CouponApplyForm(forms.Form):
    code = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "w-3/5 m-2 rounded focus:ring-0 focus:border-[#c0c0c0] bg-green-100",
                "placeholder": "Enter Coupon Code",
            }
        ),
    )

order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from store.models import Product, ProductVariant, Size
from users.models import Customer
from .models import OrderItem, Order, Coupon, ShippingAddress, PickUpDetail
from .forms import CouponApplyForm
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST
from django.utils import timezone
from django.utils.timezone import make_aware
from django.contrib import messages
import stripe
from django.conf import settings
from django.urls import reverse
from django.views.generic import TemplateView
from django.http.response import HttpResponseNotFound, JsonResponse
import json
import datetime


def get_customer_or_guest(request):
    """
    checking if current user is authenticated/customer,
    if not customer will be created based on device id
    """
    if request.user.is_authenticated:
        customer = request.user.customer
    else:
        customer, created = Customer.objects.get_or_create(
            device=request.COOKIES["device"]
        )
    return customer


def cart(request):
    """
    Cart page. It contains information about only one order,
    which has not complete (complete=False) status.
    """
    try:
        customer = get_customer_or_guest(request)
    except:
        return redirect("store:products")

    customer_order = Order.objects.filter(customer=customer, complete=False)

    # in case user visits cart directly  without adding any item
    if customer_order.exists():
        customer_items = OrderItem.objects.filter(order_id__in=customer_order).order_by(
            "product__name", "-variation__size"
        )
        customer_order = customer_order[0]
    else:
        customer_order, customer_items = None, None

    context = {
        "order": customer_order,
        "items": customer_items,
    }

    return render(request, "order/cart.html", context)


@require_POST
def add_to_cart(request, pk):
    """
    adding item to cart from the main page,
    if cart is empty order and order item will be created
    if user is not registered, device id from the cookies is used
    """
    product = get_object_or_404(Product, pk=pk)
    # getting product quantity
    quantity = int(json.loads(request.body)["quantity"])

    # getting product variation
    if product.has_variants:
        size = json.loads(request.body)["size"]
        size = Size.objects.get(name=size)
        variation = ProductVariant.objects.get(size=size, product=product)
    else:
        variation = None

    try:
        customer = get_customer_or_guest(request)
    except:
        return redirect("store:products")

    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    order_item, created = OrderItem.objects.get_or_create(
        order=order,
        product=product,
        variation=variation,
    )
    order_item.quantity += quantity
    order_item.save()
    order.save()  # to update modified field of order model
    return JsonResponse({"cart_total": order.get_cart_items})


@require_POST
def remove_from_cart(request, pk):
    """
    removing product from the cart
    """
    order_item = get_object_or_404(OrderItem, pk=pk)
    order_item.delete()
    # save corresponding order to update modified date field
    order_item.order.save()
    # redirects to the same page
    # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return redirect("order:cart")


@require_POST
def increase_product_quantity(request, pk):
    """
    adding +1 item to the cart
    this functionality is used inside the cart page
    """
    order_item = get_object_or_404(OrderItem, pk=pk)
    order_item.quantity += 1
    order_item.save()

    # save corresponding order to update modified date field
    order_item.order.save()

    # redirect to the same page
    # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return redirect("order:cart")


@require_POST
def reduce_product_quantity(request, pk):
    """
    reduce item quantity in the cart by one,
    if quantity becomes negative whole OrderItem gets deleted
    """
    # order query set
    order_item = get_object_or_404(OrderItem, pk=pk)
    if order_item.quantity > 1:
        order_item.quantity -= 1
        order_item.save()
    else:
        order_item.delete()

    # save corresponding order to update modified date field
    order_item.order.save()

    # redirect to the same page
    return redirect("order:cart")


@require_POST
def change_product_quantity(request):
    """
    Change product quantity inside the cart - uses Ajax
    """
    quantity = request.POST.get("quantity")
    order_item_id = request.POST.get("orderItemId")
    order_item = get_object_or_404(OrderItem, pk=order_item_id)
    order_item.quantity = quantity
    order_item.save()
    # save order to update modified date field
    order_item.order.save()
    return redirect("order:cart")


@require_POST
def coupon_apply(request):
    """
    Applies the coupon inside checkout.
    From the coupon code it first retrieves Coupon from the database,
    then confirms it using Stripe Coupon ID from Stripe Coupon webhook
    """
    now = timezone.now()
    form = CouponApplyForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data["code"]
        try:
            coupon = Coupon.objects.get(
                code__iexact=code, valid_from__lte=now, valid_to__gte=now, active=True
            )
            # check Coupon ID with stripe webhook
            stripe.api_key = settings.STRIPE_SECRET_KEY
            try:
                stripe_coupon = stripe.Coupon.retrieve(coupon.stripe_coupon_id)
                if stripe_coupon["valid"] == True:
                    messages.success(request, "Coupon applied")
                else:
                    raise ValueError
            except:
                raise ValueError

            customer = get_customer_or_guest(request)
            order = Order.objects.get(customer=customer, complete=False)
            order.coupon = coupon
            order.save()
        except Coupon.DoesNotExist:
            messages.error(request, "Coupon does not exist")
        except ValueError:
            messages.error(request, "Coupon cannot be verified")
    else:
        messages.error(request, "Coupon code is invalid")
    return redirect("order:checkout")


@require_POST
def coupon_remove(request):
    """
    remove coupon from the cart
    """
    if request.method == "POST":
        customer = get_customer_or_guest(request)
        order = Order.objects.get(customer=customer, complete=False)
        order.coupon = None
        order.save()
    return redirect("order:checkout")


def checkout(request):
    """Checkout view"""

    # pass stripe publishable key for checkout session
    stripe_publishable_key = settings.STRIPE_PUBLISHABLE_KEY
    # to catch a case when user visits checkout page without visiting main page
    try:
        customer = get_customer_or_guest(request)
    except:
        return redirect("store:products")
    # order query set
    order_qs = Order.objects.filter(customer=customer, complete=False)
    # if order exists, get all order items
    if order_qs.exists():
        order = order_qs[0]
        order_items = OrderItem.objects.filter(order=order)
        # coupon form
        coupon_form = CouponApplyForm()

        context = {
            "order": order,
            "order_items": order_items,
            "coupon_form": coupon_form,
            "stripe_publishable_key": stripe_publishable_key,
        }
        # redirect to the main page if there are not items in the cart
        if order.get_cart_items < 1:
            return redirect("store:products")
    else:
        # redirect to main page if there are not oustanding orders
        return redirect("store:products")
    return render(request, "order/checkout.html", context=context)


@require_POST
def cash_checkout(request, pk):
    """
    Finalizing order with deferred payment - Cash payment
    """

    errors = []

    def catch_validation_errors(e):
        """
        Collect errors and return Unprocessable Entity HTTP response
        """
        for key, value in e:
            validation_error = key.upper() + " " + value[0]
            errors.append(validation_error)

    order = get_object_or_404(Order, transaction_id=pk)
    order.payment_method = "cash"
    # load data from POST to check delivery method
    try:
        data = json.loads(request.body)
    except:
        return HttpResponseNotFound()

    delivery = data.pop("delivery")

    # pop email and phone
    phone = data.pop("phone")
    email = data.pop("email")

    if delivery:
        order.delivery_method = "delivery"
        try:
            # manually trigger fields validation without saving a model
            ShippingAddress(**data).full_clean()
            # get or create Shipping Address (already saves data)
            shipping_address, created = ShippingAddress.objects.get_or_create(**data)
            # update shipping in order
            order.shipping = shipping_address
        except Exception as e:
            catch_validation_errors(e)
    else:
        order.delivery_method = "carryout"
        try:
            if data["urgency"] == "custom":
                # change data format and make naive datetime object timezone aware
                data["pickup_date"] = make_aware(
                    datetime.datetime.strptime(data["pickup_date"], "%Y-%m-%d %I:%M %p")
                )
            elif data["urgency"] == "asap":
                # for asap pick up date use today's date
                data["pickup_date"] = timezone.now().replace(
                    hour=0, minute=0, second=0, microsecond=0
                )
            # validate PickUp details
            PickUpDetail(**data).full_clean()
            # get or create PickUpDetail (already saves data)

order/templates/order/cart.html
{% extends 'store/base.html' %} {% block content %} {% if not items %}
<div class="container mx-auto mt-10">
  <div class="w-full bg-white p-10 text-center">
    <h2 class="font-bold">Your cart is empty</h2>
    <div>
      <a
        href="{% url 'store:products' %}"
        class="flex font-semibold text-indigo-600 text-sm my-5 w-1/4"
      >
        <svg
          class="fill-current mr-2 text-indigo-600 w-4"
          viewBox="0 0 448 512"
        >
          <path
            d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"
          />
        </svg>
        Continue Shopping
      </a>
    </div>
  </div>
</div>
{% else %}
<div class="container mx-auto mt-10">
  <div class="flex flex-col shadow-md my-10">
    <div class="w-full bg-white p-3 md:p-10">
      <a
        href="{% url 'store:products' %}"
        class="flex font-semibold text-indigo-600 text-sm my-5 w-1/4"
      >
        <svg
          class="fill-current mr-2 text-indigo-600 w-4"
          viewBox="0 0 448 512"
        >
          <path
            d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"
          />
        </svg>
        Continue Shopping
      </a>
      <div class="flex justify-between border-b pb-8">
        <h1 class="font-semibold text-2xl">Shopping Cart</h1>
        <h2 class="font-semibold text-2xl">{{order.get_cart_items}} Item(s)</h2>
        <h2 class="font-semibold text-2xl">
          Total: ${{order.get_cart_subtotal|floatformat:2}}
        </h2>
      </div>

      <div
        class="flex mt-10 mb-5 font-semibold text-center text-gray-600 text-xs uppercase"
      >
        <h3 class="w-2/5">Product Details</h3>
        <h3 class="w-1/5 text-center">Quantity</h3>
        <h3 class="w-1/5 text-center">Price</h3>
        <h3 class="w-1/5 text-center">Total</h3>
      </div>
      {% for item in items %}
      <div class="flex items-center hover:bg-gray-100 -mx-8 px-6 py-5">
        <div class="flex w-2/5">
          <!-- product -->
          <div class="w-20">
            <img
              class="h-20 rounded-xl"
              src="{{item.product.image.url}}"
              alt=""
            />
          </div>
          <div class="flex flex-col justify-between ml-4 flex-grow">
            <span class="font-bold text-sm">{{ item.product.name|title }}</span>
            <span class="text-green-500 text-xs"
              >{{item.variation.size.name}}</span
            >
            <form
              action="{% url 'order:remove-from-cart' item.id %}"
              method="post"
            >
              {% csrf_token %}
              <button
                type="submit"
                class="font-semibold hover:text-red-500 text-gray-500 text-xs"
              >
                Remove
              </button>
            </form>
          </div>
        </div>
        <div
          class="flex justify-center items-center w-1/5 individual-container"
        >
          <form
            action="{% url 'order:reduce-product-quantity' item.pk %}"
            method="post"
          >
            {% csrf_token %}
            <button type="submit">
              <svg class="fill-current text-gray-600 w-3" viewBox="0 0 448 512">
                <path
                  d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"
                />
              </svg>
            </button>
          </form>
          <input
            class="quantity mx-2 border text-center w-12"
            type="number"
            value="{{item.quantity}}"
            min="1"
            oninput="validity.valid||(value='');"
            id="{{item.pk}}"
          />
          <form
            action="{% url 'order:increase-product-quantity' item.pk %}"
            method="post"
          >
            {% csrf_token %}
            <button type="submit">
              <svg class="fill-current text-gray-600 w-3" viewBox="0 0 448 512">
                <path
                  d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"
                />
              </svg>
            </button>
          </form>
        </div>
        <h1 class="text-center w-1/5 font-semibold text-sm">
          ${% firstof item.variation.price item.product.price %}
        </h1>

        <span class="text-center w-1/5 font-semibold text-sm"
          >${{item.get_total|floatformat:2}}</span
        >
      </div>
      {% endfor %}
      <div class="mt-5">
        <form action="{% url 'order:checkout' %}" method="POST">
          {% csrf_token %}
          <button
            type="submit"
            class="bg-indigo-500 font-semibold hover:bg-indigo-600 py-3 text-sm text-white uppercase w-1/3 flex items-center justify-center ml-auto"
          >
            Checkout
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
<script>
  // listen to the quantity input and on change send post request to update quantity
  $(document).on("change", ".quantity", function () {
    // get inputed quantity
    var quantity = $(this).val();
    // get id of the order
    var orderItemId = this.id;
    $.ajax({
      url: "{% url 'order:change-product-quantity' %}",
      type: "POST",
      data: {
        orderItemId: orderItemId,
        quantity: quantity,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      success: location.reload(),
    });
  });
</script>
{% endblock %}

order/templates/order/checkout_promo.html
<form
  action="{% url 'order:add-coupon' %}"
  method="post"
  class="flex justify-center items-center mt-5 bg-white rounded-lg shadow-xl py-3"
>
  {% csrf_token %} {{coupon_form.code}}
  <button
    type="submit"
    class="w-1/5 py-2.5 mx-2 bg-green-600 text-white rounded"
  >
    Apply
  </button>
</form>

order/templates/order/payment_failed.html
<p>Payment failed</p>

order/templates/order/payment_success.html
{% extends 'store/base.html' %} {% block content %}
<p>We recieved your order, payment was successful</p>
{% endblock %}